[ ] const wDynamicMainWindow = CDocumentsAndSettingsIvanMyDocuments
[ ] 
[-] window MainWin CDocumentsAndSettingsIvanMyDocuments
	[ ] locator "/MainWin[@caption='C:\Documents and Settings\Ivan\My Documents\']"
	[ ] 
	[ ] // The working directory of the application when it is invoked
	[ ] const sDir = "%ProgramFiles%\7-Zip"
	[ ] 
	[ ] // The command line used to invoke the application
	[ ] const sCmdLine = "%ProgramFiles%\7-Zip\7zFM.exe"
	[ ] 
	[ ] // The list of windows the recovery system is to leave open
	[ ] // const lwLeaveOpenWindows = {?}
	[ ] // const lsLeaveOpenLocators = {?}
[ ] 
[ ] 
